version: "2"
services:
  employees-db:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql

volumes:
  ? persistent
